イベント開催会場を「株式会社インプレス」に更新 (Test 2)
yuke011/ichiyasaGitSample pull request #1
Opened 2023-12-11 20:12 UTC by yuke011

＃＃＃　変更内容
イベント開催会場を「株式会社インプレス」に更新しました。

＃＃＃　背景
「株式会社インプレス」さんがイベント会場を提供してくださることになりました。

2023-12-12 20:33 UTC, yukina5465 commented
OK（TestA）問題ないのでマージします。

2023-12-12 20:43 UTC, yukina5465 requested changes

2023-12-12 20:43 UTC, yukina5465 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
「株式会社インプレス2」に変更して頂けますか。

2023-12-13 20:38 UTC, yuke011 commented
株式会社インプレス2に変更しました。

2023-12-13 20:42 UTC, yukina5465 commented
> 株式会社インプレス2に変更しました。

2023-12-13 20:46 UTC, yukina5465 approved these changes
2 が付いていること確認しました。

2023-12-13 21:02 UTC, merged